### ISSUE TITLE
[Feature Request]: Add option to keep the thumbar buttons always enabled instead of being disabled due to context

### ISSUE THREAD

**Issue by NaiveInvestigator** [qwerty12/mpv-taskbar-buttons#2]
>If you edit the playlist and the current file suddenly becomes the first or last (or in the middle if it wasn't before), the buttons probably won't reflect that.

My reasoning for this is that it would sort of mitigate the above mentioned issue. I highly doubt that ppl will be annoyed that their button is not disabled if a song is in the beginning or end of a playlist or being context aware. But if they do want that for some reason we can keep that enabled by default using a flag or something and make it editable in `mpv-taskbar-buttons.conf` or something.

**Comment by qwerty12** [comment]
Hi,

Pretty much as you said: If you make a mpv-taskbar-buttons.conf file in your script-opts folder and add the line `never_disable_buttons=yes` to it, the buttons should always stay enabled. I think the quoted issue can be sorted by reacting to changes in the playlist-count but I'm just too lazy to do it.
