### ISSUE TITLE
[Feature Request]: Add support for uosc script

### ISSUE THREAD

**Issue by NaiveInvestigator** [qwerty12/mpv-taskbar-buttons#3]
As I have realized once i started using this script is that now uosc has its own playlist, shuffling method and it breaks autoload.lua. Which is why I just use the autoload function that comes with uosc and that just directly plays the next file without using a playlist. This results in when i click to play a song and press the next button, it doesn't work since there is no next file according to mpv, but if we use `script-binding uosc/next` it works.

So if we could just change the thumb button command to use uosc's navigation functions if uosc is installed would be awesome!

Which is why I asked for this feature #2 lol since uosc doesn't use a playlist to load files and that in turn disables both the buttons since mpv thinks there is no next file.

I hope I am making sense. Sorry for the long rambling ;-;

**Comment by qwerty12** [comment]
Hi again,

You should be able to add the following (+ `play_pause_command`) to script-opts\mpv-taskbar-buttons.conf

```
prev_command=script-binding uosc/prev
next_command=script-binding uosc/next
```

While I use uosc myself, I don't want to add detection for it in the script. For more advanced options than just running a command (or multiple ones separated by ; ), I'd probably just edit the functions directly in `local callbacks = {` in hook.lua
