### ISSUE TITLE
Does not work with mpv.net

### ISSUE THREAD

**Issue by lorenzodbr** [qwerty12/mpv-taskbar-buttons#5]
As the title says, I tried to use the script within mpv.net, but it produces the following error in the console: `Couldn't find mpv window handle`. I also tried changing `line 61` of `common.lua` by replacing `mpv` with `mpvnet` but it didn't work out. I'm not into `lua` and Windows APIs enough to fix this by myself.

**Comment by qwerty12** [comment]
Apparently, you should replace `mpv` in common.lua with `WindowsForms10.Window.8.app.0.201d787_r3_ad1`. Whether future releases of mpv.net will continue to have the same window class name is anyone's guess. And `C.GetModuleHandleA(nil)` in hook.lua should be replaced with `C.GetModuleHandleA("libmpv-2.dll")`. Not a clue if this will actually work.

**Comment by lorenzodbr** [comment]
Tried your solution but the same error shows up.

> `WindowsForms10.Window.8.app.0.201d787_r3_ad1`

How did you get that classname of `mpv.net`?

**Comment by qwerty12** [comment]
I see. Upon starting mpv.net for the second time, I now get `WindowsForms10.Window.8.app.0.1563fc2_r3_ad1`.

Revert any changes you may have made to this script and apply this patch:

```diff
diff --git a/common.lua b/common.lua
index 24846cb..9139651 100644
--- a/common.lua
+++ b/common.lua
@@ -12,8 +12,10 @@ local function get_script_directory()
 end
 
 ffi.cdef [[
-    void* __stdcall FindWindowExA(void *hWndParent, void *hWndChildAfter, const char *lpszClass, const char *lpszWindow);
     unsigned int __stdcall GetWindowThreadProcessId(void *hWnd, unsigned int *lpdwProcessId);
+    unsigned int __stdcall GetClassNameA(void *hWnd, char *lpClassName, int nMaxCount);
+    typedef int (__stdcall *WNDENUMPROC)(void *hWnd, intptr_t l);
+    int __stdcall EnumWindows(WNDENUMPROC func, intptr_t l);
 
     enum {
         BUTTON_FIRST,
@@ -53,21 +55,33 @@ function common.read_options()
 end
 
 function common.get_mpv_hwnd()
+    local wanted = "WindowsForms10"
     local our_pid = mp.get_property_number("pid")
+    local class_name_buf = ffi.new("char[50]")
     local hwnd_pid = ffi.new("unsigned int[1]")
-    local hwnd = nil
 
-    repeat
-        hwnd = C.FindWindowExA(nil, hwnd, "mpv", nil)
-        if hwnd ~= nil then
-            local thread_id = C.GetWindowThreadProcessId(hwnd, hwnd_pid)
-            if hwnd_pid[0] == our_pid then
-                return hwnd, thread_id
+    local ret_hwnd = nil
+    local ret_thread_id = 0
+
+    local cb = ffi.cast("WNDENUMPROC", function(hwnd, _)
+        local thread_id = C.GetWindowThreadProcessId(hwnd, hwnd_pid)
+        if hwnd_pid[0] == our_pid then
+            local written = C.GetClassNameA(hwnd, class_name_buf, 50)
+            if written then
+                if ffi.string(class_name_buf, written):sub(1, #wanted) == wanted then
+                    ret_hwnd = hwnd
+                    ret_thread_id = thread_id
+                    return false
+                end
             end
-        else
-            return nil, 0
         end
-    until false
+        return true
+    end)
+
+    C.EnumWindows(cb, 0)
+    cb:free()
+
+    return ret_hwnd, ret_thread_id
 end
 
 return common
diff --git a/hook.lua b/hook.lua
index 0db9b12..9fda82e 100644
--- a/hook.lua
+++ b/hook.lua
@@ -81,7 +81,7 @@ local INFINITE, WAIT_OBJECT_0 = 0xFFFFFFFF, 0x00000000
 local GPTR = 0x0040
 local PAGE_EXECUTE_READWRITE = 0x40
 local SetEvent = C.GetProcAddress(C.GetModuleHandleA("kernel32.dll"), "SetEvent")
-local mpv_set_wakeup_callback = ffi.cast("mpv_set_wakeup_callback", C.GetProcAddress(C.GetModuleHandleA(nil), "mpv_set_wakeup_callback"))
+local mpv_set_wakeup_callback = ffi.cast("mpv_set_wakeup_callback", C.GetProcAddress(C.GetModuleHandleA("libmpv-2.dll"), "mpv_set_wakeup_callback"))
 
 local last_button_hit = ffi.cast("int*", C.GlobalAlloc(GPTR, ffi.sizeof("int"))) -- not actually thread safe...
 local script_ctx = ffi.cast("struct script_ctx*", debug.getregistry()["ctx"]) -- hell yeah, Lua(JIT)
```

The above is enough to have this load in mpv.net and seemingly work. However, if this script causes crashes further on down the line, then I can't help you, sorry; this script was written solely with the original mpv in mind and I have no idea how mpv.net differs.

> How did you get that classname of mpv.net?

I opened System Informer and looked at its Windows tab for a running mpvnet.exe process. Alternatives would include the venerable Spy++ included with Visual Studio, m417z's WinSpy++, Window Detective, Window Inspector and AutoHotkey's (AutoIt too, I think) included Window Spy.

If the class name starts with something different on your system, change `wanted` as necessary.

**Comment by lorenzodbr** [comment]
Perfect, it seems to work. Thanks for your time and dedication!
